openapi: 3.0.2
info:
  title: PTT-P25
  description: A radio talk path, typically a P25 or analog talkgroup on a conventional or trunked radio system. However, may be operating in direct (talk-around) mode or through a conventional radio repeater. The only required are channelId, WACN, systemId and groupMode. The channelAlias field is required if known. All other fields are optional.
  contact:
    name: NENA
    email: commleadership@nena.org
  version: '1.0.0'
components:
  schemas:
    PTT-P25:
      title: PTT-P25
      type: object
      required:
        - channelId
        - WACN
        - systemId
        - groupMode
      properties:
        mode:
          enum:
          - A
          - D
          - M
          description: The mode for the talkpath; "A" (analog), "D" (digital) or "M" (mixed).
        channelAlias:
          type: string
          description: The alias or common name associated with a talk path or radio channel. Required if known. For example, 'LTAC-1'.
        channelId:
          type: string
          description: The P25 talkgroup ID for the talkpath or the channel identifier, if available. May be in hex or decimal format.
        channelUplinkFrequency:
          type: string
          description: The uplink frequency for the talkpath, if operating in direct or conventional mode.
        channelDownlinkFrequency:
          type: string
          description: The downlink frequency for the talkpath, if operating in direct or conventional mode.
        rxCode:
          type: string
          description: The Network Access Code (NAC) or Continuous Tone-Coded Squelch System (CSTCSS) code for the downlink talkpath, if available. May be presented in hex or decimal format.
        txCode:
          type: string
          description: The Network Access Code (NAC) or Continuous Tone-Coded Squelch System (CSTCSS) code for the uplink talkpath, if available. May be presented in hex or decimal format.
        channelEncrypted:
          type: boolean
          description: Indicates whether the talk path is encrypted.
        systemAlias:
          type: string
          description: The alias or common name for radio system. Typically the name for a radio system. For example, 'Allied Matrix for Emergency Response'.
        WACN:
          type: string
          description: The Wide Area Communications Network  code for the system. This with the SystemID uniquely identifies a trunked radio system.
        systemId:
          type: string
          description: The system ID for a trunked radio system. This with the WACN uniquely identifies a trunked radio system.
        units:
          type: array
          items:
            type: object
            properties:
              alias:
                type: string
                description: The common name or alias for units assigned to the talk path for the incident. For example, 'Cruiser-2020-Mobile' or 'Dern Handy'.
              terminalId:
                type: string
                description: The unique ID for the radio terminal assigned to the talk path for the incident. Can be presented in hex or decimal.
              unitId:
                type: string
                description: The globally unique NG911 ID for individual units assigned to the talk path for the incident. This is the ID contained in the unit's PCA-traceable validated NG911 Certificate.
        talkMode:
          enum:
            - Group
            - Private
          description: Whether the talk path is a group or private (to a designated unitId) call. Typically, talk paths are group calls.
        groupMode:
          enum:
            - Conventional
            - trunked
          description: The type of group resource call if the talk path is a group resource. 
